apiVersion: batch/v1
kind: Job
metadata:
  name: init-mysql-db
  labels:
    {{- include "wordpress-client.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        {{- include "wordpress-client.labels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      serviceAccountName: db-init-sa
      initContainers:
        # First: Get MySQL root password and generate user password
        - name: get-secrets
          image: bitnami/kubectl:latest
          command:
            - /bin/bash
            - -c
            - |
              set -e
              # Get MySQL root password
              kubectl get secret {{ .Values.mysql.rootSecretName }} -n mysql-system -o jsonpath='{.data.{{ .Values.mysql.rootSecretKey }}}' | base64 -d > /shared/mysql-root-password
              # Generate random password for WordPress DB user
              cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 24 | head -n 1 > /shared/db-password
              echo "Secrets retrieved and password generated"
          volumeMounts:
            - name: shared
              mountPath: /shared
        # Second: Create database and user
        - name: create-db
          image: mysql:8.0
          command:
            - /bin/bash
            - -c
            - |
              set -e
              MYSQL_ROOT_PASSWORD=$(cat /shared/mysql-root-password)
              DB_PASS=$(cat /shared/db-password)
              DB_NAME="{{ include "wordpress-client.dbName" . }}"
              DB_USER="{{ include "wordpress-client.dbUser" . }}"

              echo "Creating database: ${DB_NAME}"
              echo "Creating user: ${DB_USER}"

              mysql -h {{ .Values.mysql.host }} -P {{ .Values.mysql.port }} -u root -p"${MYSQL_ROOT_PASSWORD}" \
                {{- if .Values.mysql.tls.enabled }}
                --ssl-mode=REQUIRED \
                {{- end }}
                -e "
              CREATE DATABASE IF NOT EXISTS \`${DB_NAME}\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
              CREATE USER IF NOT EXISTS '${DB_USER}'@'%' IDENTIFIED BY '${DB_PASS}';
              GRANT ALL PRIVILEGES ON \`${DB_NAME}\`.* TO '${DB_USER}'@'%';
              FLUSH PRIVILEGES;
              "
              echo "Database and user created successfully"
          volumeMounts:
            - name: shared
              mountPath: /shared
      containers:
        # Third: Create Kubernetes secret
        - name: create-secret
          image: bitnami/kubectl:latest
          command:
            - /bin/bash
            - -c
            - |
              set -e
              DB_PASS=$(cat /shared/db-password)
              DB_NAME="{{ include "wordpress-client.dbName" . }}"
              DB_USER="{{ include "wordpress-client.dbUser" . }}"

              kubectl create secret generic wordpress-db-credentials \
                --namespace={{ .Release.Namespace }} \
                --from-literal=username="${DB_USER}" \
                --from-literal=password="${DB_PASS}" \
                --from-literal=database="${DB_NAME}" \
                --from-literal=host="{{ .Values.mysql.host }}" \
                --from-literal=port="{{ .Values.mysql.port }}" \
                --dry-run=client -o yaml | kubectl apply -f -

              echo "Secret created successfully"
          volumeMounts:
            - name: shared
              mountPath: /shared
      volumes:
        - name: shared
          emptyDir: {}
