apiVersion: batch/v1
kind: Job
metadata:
  name: init-mysql-db
  labels:
    {{- include "wordpress-client.labels" . | nindent 4}}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
    {{- include "wordpress-client.labels" . | nindent 8}}
    spec:
      restartPolicy: Never
      serviceAccountName: db-init-sa
      containers:
        - name: init-db
          image: mysql:8.0
          command:
            - /bin/bash
            - -c
            - |
              set -e

              # Variables
              DB_NAME="{{ include "wordpress-client.dbName" . }}"
              DB_USER="{{ include "wordpress-client.dbUser" . }}"
              DB_PASS=$(openssl rand -base64 16 | tr -d '=+/')

              echo "Creating database: ${DB_NAME}"
              echo "Creating user: ${DB_USER}"

              # Connect to MySQL and create database + user
              mysql -h {{ .Values.mysql.host }} -P {{ .Values.mysql.port }} -u root -p"${MYSQL_ROOT_PASSWORD}" \
                {{- if .Values.mysql.tls.enabled }}
                --ssl-mode=REQUIRED \
                {{- end }}
                << EOF
              CREATE DATABASE IF NOT EXISTS \`${DB_NAME}\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
              CREATE USER IF NOT EXISTS '${DB_USER}'@'%' IDENTIFIED BY '${DB_PASS}';
              GRANT ALL PRIVILEGES ON \`${DB_NAME}\`.* TO '${DB_USER}'@'%';
              FLUSH PRIVILEGES;
              EOF

              echo "Database and user created successfully"

              # Create Kubernetes secret with credentials
              cat <<EOF | kubectl apply -f -
              apiVersion: v1
              kind: Secret
              metadata:
                name: wordpress-db-credentials
                namespace: {{ .Release.Namespace }}
              type: Opaque
              stringData:
                username: "${DB_USER}"
                password: "${DB_PASS}"
                database: "${DB_NAME}"
                host: "{{ .Values.mysql.host }}"
                port: "{{ .Values.mysql.port }}"
              EOF

              echo "Secret created successfully"
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{.Values.mysql.rootSecretName}}
                  key: {{.Values.mysql.rootSecretKey}}
