apiVersion: batch/v1
kind: Job
metadata:
  name: init-mysql-db
  labels:
    {{- include "wordpress-client.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        {{- include "wordpress-client.labels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      serviceAccountName: db-init-sa
      containers:
        - name: init-db
          image: bitnami/kubectl:latest
          command:
            - /bin/bash
            - -c
            - |
              set -e

              # Get MySQL root password from mysql-system namespace
              MYSQL_ROOT_PASSWORD=$(kubectl get secret {{ .Values.mysql.rootSecretName }} -n mysql-system -o jsonpath='{.data.{{ .Values.mysql.rootSecretKey }}}' | base64 -d)

              # Variables
              DB_NAME="{{ include "wordpress-client.dbName" . }}"
              DB_USER="{{ include "wordpress-client.dbUser" . }}"
              DB_PASS=$(openssl rand -base64 16 | tr -d '=+/')

              echo "Creating database: ${DB_NAME}"
              echo "Creating user: ${DB_USER}"

              # Install mysql client
              apt-get update && apt-get install -y default-mysql-client

              # Connect to MySQL and create database + user
              mysql -h {{ .Values.mysql.host }} -P {{ .Values.mysql.port }} -u root -p"${MYSQL_ROOT_PASSWORD}" \
                {{- if .Values.mysql.tls.enabled }}
                --ssl-mode=REQUIRED \
                {{- end }}
                << EOSQL
              CREATE DATABASE IF NOT EXISTS \`${DB_NAME}\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
              CREATE USER IF NOT EXISTS '${DB_USER}'@'%' IDENTIFIED BY '${DB_PASS}';
              GRANT ALL PRIVILEGES ON \`${DB_NAME}\`.* TO '${DB_USER}'@'%';
              FLUSH PRIVILEGES;
              EOSQL

              echo "Database and user created successfully"

              # Create Kubernetes secret with credentials
              kubectl create secret generic wordpress-db-credentials \
                --namespace={{ .Release.Namespace }} \
                --from-literal=username="${DB_USER}" \
                --from-literal=password="${DB_PASS}" \
                --from-literal=database="${DB_NAME}" \
                --from-literal=host="{{ .Values.mysql.host }}" \
                --from-literal=port="{{ .Values.mysql.port }}" \
                --dry-run=client -o yaml | kubectl apply -f -

              echo "Secret created successfully"
