{{- if .Values.networkPolicy.enabled }}
# Default deny all ingress traffic from other namespaces
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-ingress
  labels:
    {{- include "wordpress-client.labels" . | nindent 4 }}
spec:
  podSelector: {}
  policyTypes:
    - Ingress
---
# Allow ingress from Traefik to WordPress (port 80)
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-traefik-ingress
  labels:
    {{- include "wordpress-client.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "wordpress-client.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: traefik
      ports:
        - protocol: TCP
          port: 80
---
# Allow egress for DNS and external HTTPS (plugin updates, etc.)
# Note: MariaDB and Valkey are sidecars (localhost) - no network policy needed
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-external-egress
  labels:
    {{- include "wordpress-client.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "wordpress-client.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Egress
  egress:
    # Allow DNS resolution (kube-dns)
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    # Allow external HTTPS (for plugin/theme updates, API calls)
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
            except:
              - 10.0.0.0/8
              - 172.16.0.0/12
              - 192.168.0.0/16
      ports:
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 80
{{- end }}
