{{- if .Values.persistence.enabled }}
{{- $plan := .Values.plan | default "basic" }}
{{- $planResources := index .Values.plans $plan }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-content
  labels:
    {{- include "wordpress-client.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.persistence.storageClass }}
  resources:
    requests:
      storage: {{ $planResources.wpStorage }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-mysql
  labels:
    {{- include "wordpress-client.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.persistence.storageClass }}
  resources:
    requests:
      storage: {{ $planResources.dbStorage }}
{{- end }}
