{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace "wordpress-db-credentials" }}
{{- $dbPassword := "" }}
{{- $rootPassword := "" }}
{{- if $existingSecret }}
{{- $dbPassword = index $existingSecret.data "password" | b64dec }}
{{- $rootPassword = index $existingSecret.data "root-password" | b64dec }}
{{- else }}
{{- $dbPassword = randAlphaNum 24 }}
{{- $rootPassword = randAlphaNum 32 }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: wordpress-db-credentials
  labels:
    {{- include "wordpress-client.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ $dbPassword | b64enc | quote }}
  root-password: {{ $rootPassword | b64enc | quote }}
